### ISSUE TITLE
Could/ should it be possible to specify the database port number?

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Database#10]

**Comment by j4m3s** [comment]
Suspect this is possible using the `Settings::setConfig([ "port" => "3306" ]);` function added in commit b4deed6?  

I do think there's merit in having the db port as a first-class citizen in the Settings constructor though, alongside the host and db name.

**Comment by g105b** [comment]
Agreed. Will be in v1.

**Comment by g105b** [comment]
At first, I was going to suggest that this issue was invalid, due to wanting to remain compatible with `Illuminate\Database\Capsule\Manager`'s constructor, however I have already made the call to break compatibility for the following reason.

I consider the order of constructor parameters as important for this fundamental API design. For all database drivers, there should be no obsolete parameters that come before required parameters. This is **not** the case for Illuminate's parameter order. 

For example, when connecting to SQLite a hostname is obsolete, but a database name is required. Therefore, the database name parameter should come before the hostname parameter - this is how it is currently handled in `Gt\Database\Connection\Settings` but is not the case for Illuminate's constructor, meaning that `null` values are always present in the constructor for Illuminate Database - a design I don't want to use.

Having already broken compatibility with Illuminate, the question is where should the port number come in the order of parameters?

**Currently the port can be passed in the `$host` parameter like so: **

````php
$settings = new Settings(
	"/path/to/query",
	Settings::DRIVER_MYSQL,
	"my_database",
	"db.example.com:3306",		// NOTE: The port being passed in the "host" parameter.
	"db_user",
	"db_password123"
);
```

So the question is where is the best place in the parameter order for a port to be specified, if anywhere? I'm spending a lot of effort in making this decision because it's so fundamental to how code connects to the database, including a lot of projects that I'm already working on.

**Comment by j4m3s** [comment]
Following your design principle, port would also be obsolete for SQLite, so the earliest it could come would be after host.  It's logical that it would be immediately after host - but if you want to make it an optional parameter so that it defaults to the db default value then maybe the end of the list would be the right place for it.  

So the question is: will it be optional?

**Comment by g105b** [comment]
To answer the debate:

+ Who will be annoyed/confused if the port number isn't a parameter? Possibly somebody.
+ Who will be annoyed/confused if the port number is a parameter? Probably nobody.

Having the port number after the hostname is only going to make the connection explicitly obvious. To satisfy the problem of not being able to remember default ports, something like `Settings::DEFAULTPORT_MYSQL` and `Settings::DEFAULTPORT_POSTGRES` could be used.

**Comment by g105b** [comment]
Merged, ready for next release.
