### ISSUE TITLE
CRUD methods.

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#19]
On the Query, need to be able to call these methods and their synonyms:

+ [ ] Create / Insert
+ [ ] Retrieve / Get
+ [ ] Update
+ [ ] Delete

**Comment by j4m3s** [comment]
Would it make more sense to instantiate a Create object rather than a Query object?  Same for Retrieve, Update, Delete.  
Or if individual methods on a single class are the way to go, should each method return a different Result object?  For example, CUD do not return rows and should not be iterable - but Retrieve is/ should be.

**Comment by g105b** [comment]
Moved this to v2, because it isn't necessary to get a fully working repository.

**Comment by j4m3s** [comment]
@g105b would you accept a PR for this so it makes it into v1?  I've implemented my own proxy class that works great but it would be good to be able to drop this and get these functions into the core library instead.

**Comment by g105b** [comment]
If the PR was merged into v2, would that work for you? If not, I can't see a problem with getting it into v1 quickly.

**Comment by j4m3s** [comment]
If the PR waits until more than a week or two I'll end up on my own branch I think - I wouldn't want to wait for ages for it if it's already built.  Is there a reason not to include it in v1?  Working on the implementation has already flushed-out and fixed a couple of other defects in v1 so if I end up working on a separate fork those bugfixes would be stranded there too because of  a mire of separate-branch-per-PR complexity.

**Comment by g105b** [comment]
The only reason I am considering an alternative to a master merge is so that v1 holds just the basic original feature set. 

Either way, I will merge the PR as soon as it's made, I just wondered if it would make any sense, or would be possible, for this to be put onto the v2 branch? It won't be considered stable by Composer, but I don't think the v2 branch will be hanging around too long anyway.

**Comment by j4m3s** [comment]
Ah I see, yes that would be fine too - either the v1 or v2 branch then.  But why would you want to hold v1 to the basic original feature set if the additional features are tested and ready to go too?

**Comment by g105b** [comment]
The same reason I prefer keeping commit history rather than squashing - also when I see a relatively new project with few contributors, having an active and strict version plan is something that gives me confidence. There's no technical reason we can't include it in v1, I just thought it would help show progress on the project at this early stage... if you think this is stupid please say so as I know I have some weird ideas.

**Comment by j4m3s** [comment]
I agree about active development but not sure about the strict version plan.  Personally I'd rather see PR's picked up and either accepted, commented or rejected quickly.  Stagnant PRs is one of the first things I look for.  That said, you're proposing to accept it onto a v2 branch anyway so it's probably not really relevant.

I guess the closure of v1 release features should be a priority for members/maintainers.

**Comment by j4m3s** [comment]
Will open the PR and you can decide where to put it/ what to do with it. I have an implementation question so will ask it on the PR.
