### ISSUE TITLE
Comments with question marks

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#3]
http://stackoverflow.com/questions/26633675/pdo-comment-error

PDO parses text within comments. Any comments should be stripped from incoming SQL. This is easy enough for lines starting with `#` or `--`.

**Comment by j4m3s** [comment]
Comments don't have to start at the beginning of the line - they can be at the end of a line containing sql too.  That means you'll need to strip from the comment marker to the end of the line, which sounds simple but... What if an enclosed string within the sql contains a hash?

**Comment by g105b** [comment]
Good point. All very testable.

**Comment by j4m3s** [comment]
Also need to test for other comment markers including -- and, more annoyingly, c++ style multi line comments (/* to */)

**Comment by j4m3s** [comment]
Nice regex here for stripping them, appears to handle multi-level too: http://stackoverflow.com/a/13821950

They make the point elsewhere that you probably want to replace the comments with whitespace rather than deleting them, otherwise debugging the sql gets very hard as the line and character numbers don't match the source file any more.

**Comment by g105b** [comment]
Can close once an integration test proves this is Illuminate's responsibility.
