### ISSUE TITLE
Migrations.

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#8]
Automatically handle sequential migrations.

+ Per database, create a `gt_migration` table (configurable) and store a row for the currently-migrated sequence number.
+ Before a migration occurs, snapshot the database.
+ Attempt to apply each migration in sequence.
+ Rollback to the snapshot if any error occurs.
+ Update the migration table row with the new sequence number on success.

Anything else to consider?

**Comment by j4m3s** [comment]
Not sure whether you need to do the snapshotting for the user - what if it's a prod database?  Or Azure/ RDS etc?  Maybe have it configurable.

Flyway store an MD5 of the migration code in the migration table.  Not sure why.

I think you'd want to do this through CLI wouldn't you, rather than on every page request?  Or maybe on a special URL?

**Comment by g105b** [comment]
Yes, planning to add `gt migrate` to the CLI stuff.
